language: dita
install:
- echo "Installed"
script:
- sh .travis/publish.sh
after_success:
- sh .travis/deploy.sh
env:
  global:
  - DITAMAP=https://github.com/syncroWebapp/qa/blob/master/dita/flowers/flowers.ditamap
  - DITAVAL=https://github.com/syncroWebapp/qa/blob/master/dita/flowers/conditions.ditaval
  - ANT_OPTS=-Xmx1024M
before_install:
- openssl aes-256-cbc -K $encrypted_39c3f1c68f4a_key -iv $encrypted_39c3f1c68f4a_iv
  -in licenseKey.txt.enc -out licenseKey.txt -d
